replicaCount: 1

image:
  repository: 629490206392.dkr.ecr.eu-central-1.amazonaws.com/demo/backend
  tag: 8
  pullPolicy: Always
  containerPort: 5000

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: "128m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 10m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  hosts:
    - host: api.zbteky.shop
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: api-tls
      hosts:
        - api.zbteky.shop

affinity: {}

tolerations: []

nodeSelector: {}

env:
  PORT: 5000

secret:
  MONGO_URL: mongodb://demo-user:demo123@18.185.99.13:27017/demodb

strategy:
  enabled: true
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 25%

#Scaling configurations - edit this if you need to enable scaling for stateless applications.
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

vpa:
  enabled: true
  # Update the values here based on the application requirment.
  minAllowed:
    cpu: "100m"
    memory: "128Mi"
  maxAllowed:
    cpu: "250m"
    memory: "256Mi"

readinessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5

livenessProbe:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 5

