# templates/vpa.yaml
{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-vpa
  namespace: {{ .Release.Namespace }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  updatePolicy:
    updateMode: Auto
  resourcePolicy:
    containerPolicies:
      - containerName: {{ .Release.Name }}
        controlledResources: ["cpu", "memory"]
        minAllowed:
          cpu: {{ .Values.vpa.minAllowed.cpu | quote }}
          memory: {{ .Values.vpa.minAllowed.memory | quote }}
        maxAllowed:
          cpu: {{ .Values.vpa.maxAllowed.cpu | quote }}
          memory: {{ .Values.vpa.maxAllowed.memory | quote }}
{{- end }}

